name:                typogenetics
version:             0.1.0.0
github:              "lpalma/typogenetics"
license:             BSD3
author:              "Luciano Palma"
maintainer:          "lucianopalma90@gmail.com"
copyright:           "(c) 2017 Luciano Palma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lpalma/typogenetics#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  typogenetics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typogenetics

tests:
  typogenetics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typogenetics
    - hspec == 2.5.*
